{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ default (include "helpers.app.name" $) .Values.ingress.name }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}{{- toYaml . | nindent 4 }}{{- end }}
spec:
  ingressClassName: {{ default "nginx" .Values.ingress.className }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 2 }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ default "/" .path  }}
            pathType: {{ default "Prefix" .pathType }}
            backend:
              service:
                name: {{ default (include "helpers.app.name" $) .serviceName }}
                port:
                  number: {{ .servicePort }}
        {{- end }}
  {{- end }}
{{- end }}





