apiVersion: v1
kind: Service
metadata:
  name: {{ default (include "helpers.app.name" $) .Values.service.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "helpers.app.labels" . | nindent 4 }}
spec:
  {{- if not (empty .Values.service.type) }}
  type: {{ .Values.service.type }}
  {{- end }} 
  ports:
  {{- range .Values.service.ports }}
  - name: {{ .name }}
    protocol: {{ .protocol | default "TCP" }}
    port: {{ .port }}
    {{- if not (empty .targetPort) }}
    targetPort: {{ .targetPort }}
    {{- end }}
    {{- if not (empty .nodePort) }}
    nodePort: {{ .nodePort }}
    {{- end }}
  {{- end }}
  selector:
    {{- include "helpers.app.selectorLabels" $ | nindent 4 }}
