apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wordpress-deployment-binding
  namespace: wordpress
subjects:
- kind: ServiceAccount
  name: wordpress-deployment
  namespace: wordpress
roleRef:
  kind: Role
  name: wordpress-deployment
  apiGroup: rbac.authorization.k8s.io